### ISSUE TITLE
Crash when integrated with Carthage

### ISSUE THREAD

**Issue by JanC** [nickoneill/PermissionScope#144]
Hi,
I'm not sure if this is directly a PermissionScope issue but I ask anyway. I integrate the library using Carthage in a Objective C project and when I run the project, it crashes on 

``` objc
[self.permission addPermission:permission message:@"We use this to calculate the daylight"];
```

The stack trace is kind of weird:

![screen shot 2016-01-07 at 2 01 10 pm](https://cloud.githubusercontent.com/assets/707703/12171101/68ff504a-b547-11e5-819b-7ce8a7cae8b3.png)

Here is a sample project that reproduces it
https://dl.dropboxusercontent.com/u/1326174/CarthageTest.zip

**Comment by nickoneill** [comment]
Hey @JanC, that's pretty strange! I noticed that if you remove that line adding the permission and just call `show`, you get an error related to not being able to find the permissionscope lib file. This might be related to how you integrated with Carthage? My small check seemed to indicate you followed the steps correctly but it doesn't seem like the library is being correctly copied into that sample project.

Also, we're in the process of fixing an issue where Carthage is pulling in old binary releases instead of the newest stuff. Try using this option first: `carthage build --no-use-binaries` and see if anything is resolved.

**Comment by JanC** [comment]
That worked 👌awesome!

```
carthage update --platform iOS --no-use-binaries
```

thanks for the great library btw (Pantry as well 😉)

**Comment by nickoneill** [comment]
:+1: !
