### ISSUE TITLE
PermissionScope becomes unresponsive after asking for Notification permissions if already user rejected

### ISSUE THREAD

**Issue by TimothyChilvers** [nickoneill/PermissionScope#31]
Steps to reproduce:

Reset simulator
In example App, tap "Do a thing"
Tap "Allow Notification"
Tap "Don't allow"

Observe: Cannot interact with app

Addenda / separate issue:
After doing the above, kill the app and restart the App (Not simulator)
Tap "Do a thing" and "Allow Notification"

Observe: Cannot interact with app

Suggestion:
Store wether or not the user has ever been asked for notification permissions in NSUserDefaults and do not show notification permissions if they have been asked for before.

**Comment by bre7** [comment]
Timothy, thanks for the detailed reports. If I recall correctly, the cause of the first bug is due to the fact that there's no way callback for notifications like other permissions so the app polls every second for changes. Unless there's something else I'm not seeing though, I'll reproduce it later.
