### ISSUE TITLE
HealthPermission changes

### ISSUE THREAD

**Issue by bre7** [nickoneill/PermissionScope#86]
As discussed in #17:

> Your approach might be a good first shot. Some alternatives I was thinking about are:
> • breaking the health items up by read / share (one config, shows as two items)
> • breaking the health items up into individual data points to be requested (needs some other design for the buttons, they would still all be requested at once)
> • providing HealthKit as a convenience API only, not allowing it to be requested in the dialog with other items (it already provides a granular interface, little need to do the same thing again)

**Comment by appinator** [comment]
@bre7 The strict mode you mentioned should work fine. I mean it is still able to deep link to the Settings.app with an alert if the user didn't give access to all HKSampleTypes.

Maybe its possible to use the HK.framework status (optional or required) from the plist? 
In case its required and a user denies access to all Samples she/he would get a alert telling him to allow it and deep link to Settings.app.
In case of optional it just shows "HK denied" like it does on other buttons.

Not sure if this makes any sense or if its even possible.

**Comment by nickoneill** [comment]
Strict mode would be an OK first step here.

Sadly, I don't see HealthKit info on the app settings screen. We would have to link to Settings > Privacy Health (not possible at the moment) or into the Health app, Sources tab.

**Comment by dukemike** [comment]
Can you provide an update on HealthKit integration or provide a reference to a branch where there is a partial implementation?

**Comment by bre7** [comment]
No ETA since there are more important things that need to be implemented first (API rework, pending status, etc)

**Comment by basememara** [comment]
Hey thanks for the awesome library and to everyone here helping with the HealthKit stuff!

I was sad to see HealthKit ripped out, although I understand about the App Store issues with non-HealthKit apps. Could it have been mitigated if we used compiler flags so the HealthKit API's don't get compiled into the app unless explicitly set?

Also, I couldn't find the ongoing work on the HealthKit support, many of the branches were deleted. Can we get a `healthkit` branch created to collaborate and create PR's against?

I tried reconstructing the HealthKit support from fragmented code via old releases and snippets. It works successfully to request the right authorization, but it never recognizes if the authorization has been set thereafter; it always says `Unknown` authorization status. Plus the "Show me" button takes you to the wrong settings area of the phone that does not have the HealthKit settings.

Here's what I got so far, let me know if I should create a PR for it:
https://github.com/basememara/PermissionScope/tree/feature/healthkit-support

Any ideas or plans on how we can revive HealthKit support?

**Comment by nickoneill** [comment]
Thanks for the work @basememara, I'm not convinced that healthkit permissions belong in permissionscope because of 1) the incredible granularity of healthkit options vs the simplicity of pscope showing only three on/off permissions and 2) the lack of similar conveniences to the rest of the permissions (i.e. being able to direct users to the settings screen). I believe we can handle the HealthKit app store issues with cocoapods subspecs (though not sure if an equivalent features exists in carthage or swiftpm).

If we were going to add healthkit support, we'd have to figure out a graceful way to handle these issues before I would want to do any major work on it. Happy to read some suggestions but we have thought about it before and it doesn't seem to fit the model that well. Perhaps some API changes at WWDC will swing us in the opposite direction.

**Comment by dukemike** [comment]
@basememara, unfortunately, HealthKit simply doesn't allow you to mimic PermissionScope-like features. I tried doing the same thing as I expect you have, but came to the same conclusion as @nickoneill that it needed ripped out. As he described, some major problems you'll run into are that:
- HealthKit does not allow you to query whether or not read permissions have been granted, only whether or not write permissions have been granted.
- Not all permissions that can be read can be written (so you can't really hack your way around it by requesting more permissions than you need).
- iOS does not have a custom scheme to allow you to open the Health app, so there's no way to go to the Health settings for an app.

**Comment by basememara** [comment]
I really appreciate the wisdom and sharing the battle scars. HealthKit is definitely a wildcard because of the security implications, and probably the new-ness of it. It's too bad since I realize the implementation is outside the scope of Periscope, it does fit within the idea of abstracting requesting authorization. 

Perhaps we should think of, instead of making HealthKit fit within the way how other permission requests work in Periscope, we should at least put in some helper utilities that can used at will as part of the unified API, such as snippets like this:

```
    /**
    Requests access to HealthKit, if necessary.
    */
    func requestHealthKit() {
        guard let healthPermission = self.configuredPermissions
            .first({ $0.type == .HealthKit }) as? HealthPermission else { return }

        switch statusHealthKit(healthPermission.healthTypesToShare, typesToRead: healthPermission.healthTypesToRead, strict: healthPermission.strictMode) {
            case .Unknown:
                HKHealthStore().requestAuthorizationToShareTypes(healthPermission.healthTypesToShare,
                    readTypes: healthPermission.healthTypesToRead,
                    completion: { granted, error in
                        if let error = error { print("error: ", error) }
                            self.detectAndCallback()
                        })
            case .Unauthorized:
                self.showDeniedAlert(.HealthKit)
            case .Disabled:
                self.showDisabledAlert(.HealthKit)
            case .Authorized:
                break
        }
    }
```

Although I can't `addPermissions` for HealthKit like other permissions, using a HealthKit abstraction utility would be really awesome. Just an idea to keep the hope alive in someway including HealthKit to alleviate the pains of permission requesting.

**Comment by bre7** [comment]
Reopen if there's enough user interest. HK would seem to be too complex for PS' scope.
